### ISSUE TITLE
Sitemap Index files

### ISSUE THREAD

**Issue by lurch** [ajgb/www-sitemap-xml#1]
Hi,
Are there plans to add support for Sitemap Index files to this module?

Andrew

**Comment by ajgb** [comment]
Yes, that's on my TODO list - should be ready in next few days.

**Comment by ajgb** [comment]
Hi,

I've just switched to XML::LibXML for writing sitemap files - could you fetch it from github and check memory usage now?

Cheers,
Alex

**Comment by lurch** [comment]
Just checked with the latest github code, (after installing XML::LibXML via PPM) and the memory usages for the 3 stages are now: 31MB, 45MB and 51MB - much better! It peaks at around 70MB between stages 2 and 3, but that's obviously _much_ better than 170MB!! :-)

Thanks for the quick update - once you've added SitemapIndex support I can then fully switch away from Search::Sitemap!
I assume you'll also be switching from Twig to LibXML for reading too?

Andrew

**Comment by ajgb** [comment]
Hi,

Reading and writing is supported by LibXML.

WWW-Sitemap-XML-1.103300 adds support for sitemap index files - just uploaded to CPAN.

Cheers,
Alex
