### ISSUE TITLE
Sitemap with comments not working

### ISSUE THREAD

**Issue by astuanax** [ajgb/www-sitemap-xml#3]
Hi, 

I have tried your WWW::Sitemap::XML module and it breaks when loading/reading xml sitemaps containing a comment at the top:

``` xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<!--
 created with Free Online Sitemap Generator www.xml-sitemaps.com 
-->
```

This happens with a lot of sitemaps as they are usually generated by some sort of service or software package that inserts a comment with their urls as free advertising. 

Maybe you can add the following fix to file lib/WWW/Sitemap/XML.pm:

``` perl
my $class = $self->_entry_class;
my $xmlNoComments = $xml->getDocumentElement->toStringC14N();
$xml = XML::LibXML->load_xml( string => $xmlNoComments );
```

This removes the comments before parsing the file. I tested it on several available sitemaps, ans seems to work fine. 

Thx/Len.

**Comment by rkleemann** [comment]
I'm not sure if this is the correct fix, but I monkey-patched WWW::Sitemap::XML::read to do the following:

```
    my @entry = grep { ! $_->nodeName->isa('XML::LibXML::Comment') }
        $url->nonBlankChildNodes;
    push @entries,
        $class->new( map { $_->nodeName => $_->textContent } @entry )
            if @entry;  
```

**Comment by ajgb** [comment]
Hi,

Thanks for notifying me about this problem - and I'm sorry for not looking into it earlier.

The current version on github should address this issue, and proper CPAN release will follow shortly.

Thank you,
Alex

**Comment by ajgb** [comment]
I've just pushed to CPAN version 2.00 which resolves the issues you have described.
