### ISSUE TITLE
Image, Video, and Mobile sitemaps/extensions

### ISSUE THREAD

**Issue by ianmcorvidae** [ajgb/www-sitemap-xml#4]
Google (though not anyone else, as far as I can tell) support several extensions of the sitemaps protocol: 
- Images (https://support.google.com/webmasters/answer/178636?hl=en)
- Video (https://support.google.com/webmasters/answer/80471?hl=en)
- Mobile (https://support.google.com/webmasters/answer/6082207?hl=en).

It'd be nice to be able to include this information in sitemaps produced by this module; for other situations like this that might arise in the future (or that already exist and I'm just not aware of!), it'd be nice to support adding extra namespaces/elements in a general way.

**Comment by ajgb** [comment]
Hi,

I've just pushed to CPAN version 2.00 which add support to those extensions and provides hints how other extensions could be added.

Thanks,
Alex
