### ISSUE TITLE
Case insensitive values

### ISSUE THREAD

**Issue by rkleemann** [ajgb/www-sitemap-xml#5]
On more than one occasion, I've run into issues with the values for changefreq being improperly cased according to the spec.  For example, this sitemap has the value "Always":

http://www.metriplica.com/pruebas/vicente/sitemap.xml

Is it possible to lowercase changefreq before sending it to the constructor?

**Comment by ajgb** [comment]
Hi,

The current version on github should address this issue, and proper CPAN release will follow shortly.

Thank you,
Alex

**Comment by ajgb** [comment]
I've just pushed to CPAN version 2.00 which resolves the issues you have described.
